### ISSUE TITLE
Unable to schedule Dataset Refreshes

### ISSUE THREAD

**Issue by rob-c28** [jamf/powerbi#1]
Receiving the following error when trying to schedule Data refreshes on a newly created report using this connector

"You can't schedule refresh for this dataset because the following data sources currently don't support refresh:
Data source for "Computers - Extension attributes"
Data source for "Computers - Applications"
Data source for "Computer Device Groups"
Data source for Computers
Discover Data Sources
Query contains unknown function name: JamfPro.Contents"

**Comment by cnkrishna** [comment]
@rob-c28 - I am assuming you are trying to schedule the report in PowerBI Service (www.powerbi.com).  Did you configure your gateway correctly?  Let me know if you are scheduling in any other way.

**Comment by rob-c28** [comment]
I followed the documentation in the project and created everything in
PowerBI Desktop.  I then published it to a team workspace on powerbi.com.
Once I published it, I can no longer refresh or schedule refreshes from
powerbi.com

What do you mean by configure the gateway correctly?

**Comment by cnkrishna** [comment]
@rob-c28  - Since your report is tied to the connector, just uploading the report report to the PowerBi service will not help.  You need to have your PowerBi connected to a Power BI Gateway where your Jamf Pro connector is deployed.  I will send you detailed instructions on how this should be done.

**Comment by cnkrishna** [comment]
When Jamf Pro connector is certified and available as part of Power BI connectors, then you dont have to do this step.

**Comment by rob-c28** [comment]
Ok I understand.  Please let me know when you can send those instructions on over

**Comment by lindah64** [comment]
@cnkrishna ,

Can you please share those instructions with me also? 

Thanks,
Linda

**Comment by Angawd** [comment]
Hi, I am facing the same issue. Can you provide me the details on how to connect?
