### ISSUE TITLE
Add support for client credentials (API Roles and Clients)

### ISSUE THREAD

**Issue by jfretheim** [jamf/powerbi#17]
In addition to username/password-based bearer token authentication, support is needed for client credentials.

**Comment by guliciuc** [comment]
Hello!
I'm not seeing the Computers - Extansion Attributes data table when importing data now. Is it a local problem on my device or has it been removed? If it was removed, are there any plans to add it back, or any way i can do it manually?

**Comment by jfretheim** [comment]
Thanks for pointing that out, @guliciuc! I agree, this is basic functionality that should be there and have filed #20 to track that work.

Happy to hear any additional feedback you have, as well.

**Comment by guliciuc** [comment]
I've just started trying out the new .mez you provided. I will post anything i find relvant. Overall, thank you for taking up updating the connector!

**Comment by jfretheim** [comment]
> Hello! I'm not seeing the Computers - Extansion Attributes data table when importing data now. Is it a local problem on my device or has it been removed? If it was removed, are there any plans to add it back, or any way i can do it manually?

Hi again @guliciuc - I wanted to let you know I had some time to work on backward compatibility of the Jamf Power BI Connector, including adding back the two Extension Attribute tables. If you have time, it would be great if you could try out the changes over on the branch for issue #27 (https://github.com/jamf/powerbi/tree/27-make-version-200-backward-compatible-with-version-100) and let me know if you come up against any problems. I don't love the data model itself, but the intention is to make it as backward-compatible as possible so existing datasets and visualizations can continue to function with minimal changes.

At this point, testing is supported for Power BI Desktop exclusively.
