### ISSUE TITLE
Unable to see Custom Connectors folder in Win 10 Power BI Desktop App

### ISSUE THREAD

**Issue by lindah64** [jamf/powerbi#2]
Hi,

I was following the install steps, but I cannot locate the Custom Connectors folder. Do you happen to know if the location is different for Windows 10 Power BI Desktop App?

Thanks,
Linda

**Comment by PazDak** [comment]
If you do not see the directory simply make it. It isn't created by default.

Kyle Pazandak

**Comment by lindah64** [comment]
Hi Kyle, 

I created the folder here: Microsoft\Power BI Desktop Store App\Custom Connectors
I added the .mez file to the folder.

I enabled "Allow any extensions to load without validation or warning". I restarted Power BI Desktop, but when I reopen and search for Jamf as a data source, nothing comes up.

Any other idea where I might be going wrong?

Thanks,
Linda

**Comment by lindah64** [comment]
Hi Kyle,

I misunderstood in the instructions, I didn't realize that I need to create 2 folders in the Documents folder. I see the connector now in the get data menu.

Thanks,
Linda

**Comment by lindah64** [comment]
Hi Kyle,

Can you please send me the instructions mentioned in the other issue describing how to refresh data automatically in Power BI online please?

Thanks,
Linda

**Comment by PazDak** [comment]
@lindah64 Did you get the instructions?

**Comment by steven5342** [comment]
How was this resolved? I am currently trying to add the Custom Connections folder. Same file path as mentioned earlier in this thread.

-Steven

**Comment by lindah64** [comment]
@steven5342 you need to create the 2 folders "Microsoft Power BI Desktop" and then "Custom Connectors" so that you have the full path. Then restart Power BI
\Documents\Microsoft Power BI Desktop\Custom Connectors

**Comment by lindah64** [comment]
@PazDak would it be possible to share the instructions mentioned in the other issue describing how to refresh data automatically using a custom connector in Power BI online please?

**Comment by kuhnamie** [comment]
@lindah64, it seems like you were able to get this working. I follow the instructions in Step 2 and create a folder called Power BI Desktop, as instructed, under the full path "C:\Users\myuser\Documents\" and then I create a subfolder to Power BI Desktop called Custom Connectors and drop the file off in there. 

Full path: C:\Users\myuser\Documents\Power BI Desktop\Custom Connectors\JamfPro.mez 

But after restarting Power BI Desktop I do not see the option listed. Am i missing something? 

-Tyler

**Comment by PazDak** [comment]
The connector is now available in the connectors list. You don't need to create anything special now. Just grab it from the store.

**Comment by mitulprajapati** [comment]
@lindah64 what you mean need to create 2 folders?

**Comment by lindah64** [comment]
> @lindah64 what you mean need to create 2 folders?

@mitulprajapati 

What I mean is that you go to your Documents folder on your PC and create a folder called "Microsoft Power BI Desktop". The open this folder and create a folder called "Custom Connectors", so you have the path \Documents\Microsoft Power BI Desktop\Custom Connectors

I hope that helps.

**Comment by Martinprchal** [comment]
Hi, i think i followed the steps exactly. I have the .mez file in the correct folder, set up the security correctly, yet, i dont see my connection in the get data tab. exact same problem has everyone in our office.
![image](https://user-images.githubusercontent.com/87083107/135594028-2fbd1fb1-decb-4d7d-8e60-f28259e20fdc.png)

**Comment by lindah64** [comment]
@Martinprchal looks like the .mez file u have in the folder is a different name to the one in the GitHub. It’s called JamfPro.mez I would suggest downloading the file again from GitHub and don’t save it to the folder without changing the name of the file.

**Comment by Martinprchal** [comment]
Yes, the name is different as the connection is different. It is connection for the google spread sheet which i found somewhere else. I belive you dont have such connection type in your GitHub. And also... how could a different name affect this?

**Comment by lindah64** [comment]
@Martinprchal  apologies this isn’t my GitHub and I only used it for a for a jamf connection so I am not sure about any other connections or how to get them to work. Sorry, best of luck.

**Comment by Martinprchal** [comment]
@lindah64 you were right. I had some mistake in my .mez file (one of the components had action set up as content instead of compile in Visual Studio). This issue appreantly caused that the .mez file was not visible in the Power BI. Now all is working well and I can connect to google sheet using secure authentication. 
Thanks so much for your help!

**Comment by PazDak** [comment]
You can actually just grab this straight from microsoft. It is in their
connectors list. Since ~ February 2020 you haven't needed to actually
install it in the directory.

I don't have an instance up and running, but where you see the other
connectors... just search Jamf in that search bar.
