### ISSUE TITLE
can't schedule auto refresh when moving the PBIX file to PowerBi cloud

### ISSUE THREAD

**Issue by guliciuc** [jamf/powerbi#21]
Hi

I tried uploading the PBIX file created with the new connector , to test it on the cloud app, and it seems that it can't refresh because the data source is dynamic? Thsi didn;t happen with the previous connector, as i used it with daily auto data refresh for more than a year.
Not sure what's the reason for it, buit if this change is from the connector side, then it kind of breaks the whole purpose of it.

![image](https://github.com/user-attachments/assets/4698ae77-b1a1-4c74-82c6-59a22ddeac9e)

**Comment by jfretheim** [comment]
Thanks for reporting!

Were you using original published/1.0.0 version of the connector or were you an early tester of the `auth-updates` branch (i.e., PR #12)?

**Comment by guliciuc** [comment]
Hi. Previously, when scheduling was ok, i was using the old beta published years ago. Now that i noticed i can't schedule the data sync anymore i was testing the new develop branch you started working on a few days ago.

**Comment by jfretheim** [comment]
I believe to test a custom connector (these branch builds will be "custom" until they are published with Microsoft) in this way, you will need to use an On Premise Gateway to do on-demand and scheduled data refreshes.

That said, I had some trouble validating that workflow with the `.mez` from the PR that adds client credential support (#17).

The `.mez` on the `testing-updates` branch should allow validation of this workflow, albeit without client credentials support. I'll admin that setting up the On Premise Gateway, Connections, and associating them with Data Sets can be a bit tricky.

**Comment by guliciuc** [comment]
Fair enough. Then the question would be, is there a plan to publish the changes being done to the connector with Microsoft, somewhere in the near future?

**Comment by jfretheim** [comment]
@guliciuc I wanted to let you know: we've merged changes from #31 to `develop` that enable testing via an On-Premise Data Gateway without doing a custom build of the connector. #32 has some notes on this (and will also be merged to `develop` soon ahead of an anticipated release).
