### ISSUE TITLE
If a Jamf Pro mobile device record does not have a model number, import of Jamf Pro data will fail with “The field 'model' of the record wasn't found.” The following entry is seen in the trace log:

### ISSUE THREAD

**Issue by sarohit** [jamf/powerbi#3]
DataMashup.Trace Error: 24579 : {"Start":"2020-03-17T04:58:13.4706373Z","Action":"TracingRowset/IRowset.GetNextRows","Exception":"Exception:\r\nExceptionType: Microsoft.Mashup.Engine1.Runtime.ValueException, Microsoft.MashupEngine, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35\r\nMessage: [Expression.Error] The field 'model' of the record wasn't found.\r\nStackTrace:\n   at Microsoft.Mashup.Host.ProviderShared.MashupFileHost.TranslatePageException(ISerializedException error)\r\n   at Microsoft.Mashup.OleDbProvider.DataHost.NonBufferingMashupEvaluator.MashupEvaluation.ExceptionResolverPageReader.Read(IPage page)\r\n   at Microsoft.Mashup.Common.IPageReaderExtensions.NotifyingPageReader.Read(IPage page)\r\n   at Microsoft.Mashup.Engine.Interface.Tracing.TracingPageReader.Read(IPage page)\r\n   at Microsoft.Mashup.Common.IPageReaderExtensions.NotifyingPageReader.Read(IPage page)\r\n   at Microsoft.OleDb.Serialization.PageReaderRowset.Microsoft.OleDb.IRowset.GetNextRows(HCHAPTER hchapter, DBROWOFFSET lRowsOffset, DBROWCOUNT cRows, DBCOUNTITEM& countRowsObtained, HROW** pRows)\r\n   at Microsoft.OleDb.Rowset.Microsoft.OleDb.IRowset.GetNextRows(HCHAPTER hReserved, DBROWOFFSET lRowsOffset, DBROWCOUNT cRows, DBCOUNTITEM& countRowsObtained, HROW** pRows)\r\n   at Microsoft.Mashup.OleDbProvider.TracingRowset.Microsoft.OleDb.IRowset.GetNextRows(HCHAPTER hReserved, DBROWOFFSET lRowsOffset, DBROWCOUNT cRows, DBCOUNTITEM& countRowsObtained, HROW** pRows)\r\n\r\n\r\n","ProductVersion":"2.76.5678.782 (19.12)","ActivityId":"00000000-0000-0000-0000-000000000000","Process":"msmdsrv","Pid":8344,"Tid":9,"Duration":"00:00:00.0063917"}
”

**Comment by jfretheim** [comment]
This issue was addressed in PR #12 and will be available in a future release. Thank you for reporting!
