### ISSUE TITLE
Unable to schedule Dataset Refreshes

### ISSUE THREAD

**Issue by Angawd** [jamf/powerbi#4]
Can connect to Power BI Desktop using Jamf connector. While adding to gateway, when the URL is provided and when I try to connect the URL specified is changed and some " \\" (back slashes) are added in the URL

**Comment by cybertunnel** [comment]
This _shouldn't_ prevent you from using the Data Gateway, but those slashes are most likely because the URL is entered as text vs a URI which would give you the normal text you are expecting.
