### ISSUE TITLE
API Credentials - Failed to Auth

### ISSUE THREAD

**Issue by ElliotWilde** [jamf/powerbi#41]
Possibly user error but when connecting using API credentials (ID:KEY), I keep getting 'Couldn't Authenticate with the credentials provided' 

![Screenshot 2024-12-04 235905](https://github.com/user-attachments/assets/2fe46619-da3e-4994-85a2-f9e979a0d592)

**Comment by jfretheim** [comment]
I'll preface this with saying: the documentation for this new version is still in the works (see #40), so definitely easy to miss part of the setup! That said, here are a couple things to try so we can troubleshoot.

Does the API Role for your API Client have the right privileges? Depending on the tables selected, it may need:
* Read Mobile Devices
* Read Computers
* Read Smart Mobile Device Groups
* Read Static Mobile Device Groups
* Read Smart Computer Groups
* Read Static Computer Groups

If the above checks out, are you able to obtain an access token with that client ID and secret using another tool (for example, Postman or `curl`)? Here's an example for `curl` that should point you in the right direction:

```
curl --location "$JAMF_PRO_URL"/api/v1/oauth/token \
  --header "Content-Type: application/x-www-form-urlencoded" \
  --data-urlencode "grant_type=client_credentials" \
  --data-urlencode "client_id=$CLIENT_ID" \
  --data-urlencode "client_secret=$CLIENT_SECRET"
```

This article has a nice "recipe" script with some sample code for obtaining an access token, as well:  [Jamf Pro API Docs - Client Credentials](https://developer.jamf.com/jamf-pro/docs/client-credentials).

**Comment by jfretheim** [comment]
Closing this issue for now--let us know if the troubleshooting steps were insufficient and we can reopen!
