### ISSUE TITLE
Extra Queries to API

### ISSUE THREAD

**Issue by cybertunnel** [jamf/powerbi#8]
So since I found the code, it looks like the connector is doing a lot of extra queries to the API which could lead to a lot of heavy load to a server. We handle 10k+ active devices and almost 13k computer records. So when a refresh is attempted it breaks the server.

The queries in question is under the `initializeGlobalRecord` function which calls on:
- `GetComputerDetails`
- `GetComputerApps`

The problem with this is the `GetComputerApps` runs another API request to https://jamfurl.jamfcloud.com/JSSResource/computers/id/$id/subset/software which should have been able to be obtained by grabbing the software through `computer[software]` under the `GetComputerDetails`. This doubles the load time since it requires 2 queries to be performed when one would have worked.

This could be achieved like the `ExtensionAttributes` function where it extracts it from an existing table. The concern is running an additional query that contains the same results as another if shaped correctly.

**Comment by jfretheim** [comment]
Thank you so much for your contributions, @cybertunnel.
